### ISSUE TITLE
How about applying travis-ci to your project?

### ISSUE THREAD

**Issue by KeonHeeLee** [ryuhangyeong/daily-health-originer#12]
Before I mentioned the topic, you worked hard until the final presentation today, 
and it was great because the topic was so interesting :)

I suggest to apply travis-ci in your project. 
It is likely to increase the reliability of your project.
How do you think this suggestion?

**Comment by ryuhangyeong** [comment]
Hello, Thank you for your attention.

Your suggestion is appreciated, but I will try to stop the project.

I have come to think a lot through this presentation. My project was so easy, common, and inconvenient. I did not get anything through the project. However, I am negative about developing and deploying the project because I want to develop a more challenging and meaningful library. Also, we will create a new one each time the time passes through the fork function. New with typescript. Of course, only very essential features.

Once again thank you for your interest and I will support your project as well.
